# Generated by Django 4.2.13 on 2024-07-06 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='name',
            new_name='FirstName',
        ),
    ]
