# Generated by Django 4.2.13 on 2024-07-06 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_middlename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='MiddleName',
            field=models.CharField(max_length=100),
        ),
    ]
