# Generated by Django 4.2.13 on 2024-07-07 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_item_middlename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='MiddleName',
        ),
    ]
