# Generated by Django 4.2.13 on 2024-07-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_item_middlename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='FirstName',
            new_name='Name',
        ),
    ]
