# Generated by Django 5.0.4 on 2024-07-07 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_firstname_item_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='Name',
            new_name='name',
        ),
    ]
