# Generated by Django 4.2.13 on 2024-07-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_item_email_item_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='telephone',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
