# Generated by Django 4.2.13 on 2024-07-09 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_item_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='age',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='bloodtype',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='civilsts',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='gsis',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='height',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='pagibig',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='sex',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='weight',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
